events {
    worker_connections 1000;
}

http {
    server {
        listen 80;

        location / {
            default_type text/plain;
            return 200 "ok";
        }
    }
    server {
        listen 8081;

        location / {
            proxy_pass http://backend:8081;
        }
    }
}