services:
  frontend:
    build:
      dockerfile: ../docker/Dockerfile-react
      context: ../stackfour-react
    ports:
      - "80:80"
  backend:
    build:
      dockerfile: ../docker/Dockerfile-server
      context: ../stackfour-server
    ports:
      - "8081-8084:8081"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: uncle
      POSTGRES_PASSWORD: paul2
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql

volumes:
  pgdata:


  