services:
  frontend:
    build:
      dockerfile: ../docker/Dockerfile-react
      context: ../stackfour-react
      args:
        API_SERVER_INSTANCES_AMOUNT: 3
    deploy:
      replicas: 3
    ports:
      - "80-82:80"
  backend:
    build:
      dockerfile: ../docker/Dockerfile-server
      context: ../stackfour-server
    deploy:
      replicas: 3
    ports:
      - "8081-8083:8081"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: uncle
      POSTGRES_PASSWORD: paul2
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql

volumes:
  pgdata:


  