FROM rust:1.96 AS builder
WORKDIR /app
COPY . /app
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12

COPY --from=builder /app/target/release/stackfour-server ./stackfour-server
EXPOSE 8081

CMD ["./stackfour-server"]