FROM rust:1.96-alpine AS builder
WORKDIR /app
COPY Cargo.lock Cargo.toml ./

# Create a dummy source file to compile and cache dependencies
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release
RUN rm -f target/release/deps/stackfour-server*

COPY . .
RUN cargo build --release

FROM debian:bookworm-slim

COPY --from=builder /app/target/release/stackfour-server ./stackfour-server
EXPOSE 8081

CMD ["./stackfour-server"]